# Generated by Django 5.2.3 on 2025-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='business_license',
            field=models.ImageField(upload_to='media/licenses/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_images',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
