# Generated by Django 5.2.3 on 2025-06-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_business_license_alter_shop_shop_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_images',
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.shop')),
            ],
        ),
    ]
