# Generated by Django 5.2.4 on 2025-07-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_shop_shop_images_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='island',
            field=models.CharField(choices=[('Upolu', 'Upolu'), ('Savaii', 'Savaii')], default='Upolu', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.CharField(choices=[('Apia', 'Apia'), ('Falealili', 'Falealili'), ('Lotofaga', 'Lotofaga'), ('Salelologa', 'Salelologa'), ('Faasaleleaga', 'Faasaleleaga'), ('Palauli', 'Palauli')], default='Apia', max_length=50),
        ),
    ]
