# Generated by Django 5.2.4 on 2025-07-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_tip_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, default='n/a', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.CharField(blank=True, default='n/a', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, default='n/a', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='region',
            field=models.CharField(choices=[('Region 1', 'Region 1'), ('Region 2', 'Region 2'), ('Region 3', 'Region 3'), ('Region 4', 'Region 4')], default='Region 1', max_length=50),
        ),
    ]
