# Generated by Django 5.2.4 on 2025-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_address_alter_shop_owner_alter_shop_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('CAFE', 'Cafe'), ('RESTAURANT', 'Restaurant'), ('OTHER', 'Other')], max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='business_pics/')),
                ('location', models.CharField(max_length=200)),
                ('business_license', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
