# Generated by Django 5.2.4 on 2025-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='media/licenses/'),
        ),
    ]
